// Cardputer ADV — on-device story chat with TinyStories-Instruct-3M (GPT-Neo).
//
// The Q4_0 model and pruned GPT-2 tokenizer are compiled into the firmware
// (model_data.cpp and tok_data.cpp, generated by
// tools/convert_tinystories_instruct.py). The engine also still runs the old
// TinyLLama-v0 export (tools/convert_tinyllama_v0.py) — the model header
// selects the architecture at boot.
//
// Chat mode wraps whatever you type into the instruction format the model was
// trained on ("Summary: <your text>\nStory:", so asking for "a dragon who
// learns to share" gets a story about exactly that. Raw mode feeds your text
// in unchanged (plain completion).
//
// G0 (BOOT button / GPIO0): toggles TTS. When enabled, the bot’s reply is
// spoken through the speaker after each response using formant synthesis.

#include <M5Unified.h>
#include <esp_random.h>
#include <driver/gpio.h>
#include <string>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include "keyboard/Keyboard.h"
#include "llm.h"
#include "ui.h"
#include "port.h"
#include "tts.h"

extern "C" const uint8_t MODEL_DATA[];
extern "C" const size_t  MODEL_DATA_LEN;
extern "C" const uint8_t TOKENIZER_DATA[];
extern "C" const size_t  TOKENIZER_DATA_LEN;

static Transformer    transformer;
static Tokenizer      tokenizer;
static Sampler        sampler;
static ChatUI         ui;
static Keyboard_Class Keyboard;

static constexpr int KV_SEQ_LEN = 80;
static constexpr float DEFAULT_TEMP = 0.8f;

enum AppState { ST_BOOT, ST_CHAT, ST_SETTINGS };
static AppState state = ST_BOOT;

static float clampf(float v, float lo, float hi) { return v < lo ? lo : (v > hi ? hi : v); }
static int   clampi(int v, int lo, int hi)       { return v < lo ? lo : (v > hi ? hi : v); }

// ---------- Settings ----------

enum ChatMode { M_CHAT, M_STORY, M_RAW };

struct Settings {
  float temp      = DEFAULT_TEMP;
  int   max_reply = 44;               // tokens per reply; -1 = unlimited (stop at KV or EOS);
                                      // -2 = unsafe (wrap KV pos, run until EOS fires)
  int   mode      = M_CHAT;
};
static Settings settings;
static int sett_sel = 0;
static constexpr int SETT_N = 4;

static const char* modeName(int m) {
  switch (m) {
    case M_CHAT:  return "chat (User/Bot)";
    case M_STORY: return "story (Summary:)";
    default:      return "raw completion";
  }
}

static void drawSettings() {
  std::string names[SETT_N]  = {"Mode", "Temperature", "Max reply tokens", "RNG seed"};
  std::string values[SETT_N];
  char tbuf[16];
  snprintf(tbuf, sizeof(tbuf), "%.1f", settings.temp);
  values[0] = modeName(settings.mode);
  values[1] = settings.temp < 0.05f ? "0.0 greedy" : tbuf;
  values[2] = settings.max_reply == -2 ? "unsafe" :
              settings.max_reply <  0  ? "unlimited" :
                                         std::to_string(settings.max_reply);
  values[3] = "reroll with , /";
  ui.showSettings("Settings", names, values, SETT_N, sett_sel);
}

static void adjustSetting(int dir) {
  switch (sett_sel) {
    case 0:
      settings.mode = (settings.mode + 3 + dir) % 3;
      break;
    case 1:
      settings.temp = roundf((settings.temp + 0.1f * dir) * 10.0f) / 10.0f;
      settings.temp = clampf(settings.temp, 0.0f, 2.0f);
      sampler.temperature = settings.temp;
      break;
    case 2:
      if      (dir < 0 && settings.max_reply == -1) settings.max_reply = -2;
      else if (dir < 0 && settings.max_reply <= 4)  settings.max_reply = -1;
      else if (dir > 0 && settings.max_reply == -2) settings.max_reply = -1;
      else if (dir > 0 && settings.max_reply <  0)  settings.max_reply = 4;
      else settings.max_reply = clampi(settings.max_reply + dir, 4, KV_SEQ_LEN - 8);
      break;
    case 3:
      llm_build_sampler(&sampler, transformer.config.vocab_size,
                        settings.temp, esp_random());
      break;
  }
  drawSettings();
}

// ---------- Chat history ----------

static constexpr int HIST_MAX = 4;
static std::string hist_user[HIST_MAX], hist_bot[HIST_MAX];
static int         hist_n = 0;

static void historyPush(const std::string& u, const std::string& b) {
  if (hist_n == HIST_MAX) {
    for (int i = 1; i < HIST_MAX; i++) { hist_user[i-1] = hist_user[i]; hist_bot[i-1] = hist_bot[i]; }
    hist_n--;
  }
  hist_user[hist_n] = u;
  hist_bot[hist_n]  = b;
  hist_n++;
}

static void historyClear() {
  for (int i = 0; i < HIST_MAX; i++) { hist_user[i] = ""; hist_bot[i] = ""; }
  hist_n = 0;
}

static void leaveSettings() {
  state = ST_CHAT;
  ui.repaint();
  ui.statusf("T=%.1f  len=%d  [tab] settings", settings.temp, settings.max_reply);
}

// ---------- TTS ----------

static bool tts_enabled = false;

// ---------- Generation ----------

struct GenState {
  bool active = false;
  int pos = 0, next = 0, token = 0, n_prompt = 0;
  int* prompt_tokens = nullptr;
  uint32_t t_start_ms = 0;
  int tokens_out = 0;
  std::string user_text;
  std::string bot_text;
  bool pending_nl = false;
  bool wrapped    = false;
} gen;

static void initModel() {
  ui.statusf("Loading model (%u KB)...", (unsigned)(MODEL_DATA_LEN / 1024));
  if (!llm_init_embedded(&transformer, MODEL_DATA, MODEL_DATA_LEN, KV_SEQ_LEN)) {
    ui.fatal("model init failed (bad header or OOM)");
  }
  ui.statusf("Tokenizer (%u KB)...", (unsigned)(TOKENIZER_DATA_LEN / 1024));
  if (!llm_tokenizer_from_memory(&tokenizer, TOKENIZER_DATA, TOKENIZER_DATA_LEN,
                                 transformer.config.vocab_size)) {
    ui.fatal("tokenizer init failed");
  }
  if (tokenizer.vocab_size != transformer.config.vocab_size) {
    ui.fatal("model/tokenizer vocab mismatch - clean rebuild needed");
  }
  llm_build_sampler(&sampler, transformer.config.vocab_size, DEFAULT_TEMP, esp_random());
}

static bool appendSegment(const std::string& text, int cap, int* n) {
  int  m = 0;
  int* tmp = (int*) malloc(sizeof(int) * (text.length() + 8));
  if (!tmp) return false;
  llm_encode(&tokenizer, text.c_str(), 0, 0, tmp, &m);
  bool ok = (*n + m <= cap);
  if (ok) { memcpy(gen.prompt_tokens + *n, tmp, m * sizeof(int)); *n += m; }
  free(tmp);
  return ok;
}

static void beginGeneration(const std::string& user_text) {
  const bool neo = (tokenizer.style == ARCH_GPTNEO);
  int mode = neo ? settings.mode : M_RAW;

  int budget = KV_SEQ_LEN - (settings.max_reply >= 0 ? settings.max_reply : 0) - 1;
  if (budget < 8) budget = 8;

  if (gen.prompt_tokens) { free(gen.prompt_tokens); gen.prompt_tokens = nullptr; }
  gen.prompt_tokens = (int*) malloc(sizeof(int) * (budget + 8));
  if (!gen.prompt_tokens) { ui.appendBot("[OOM]\n"); return; }

  int n = 0;
  if (mode == M_CHAT) {
    int* seg_toks[HIST_MAX + 1];
    int  seg_len[HIST_MAX + 1];
    std::string segs[HIST_MAX + 1];
    for (int i = 0; i < hist_n; i++)
      segs[i] = "User: " + hist_user[i] + "\nBot:" + hist_bot[i];
    segs[hist_n] = "User: " + user_text + "\nBot:";

    int total = 0;
    for (int i = 0; i <= hist_n; i++) {
      seg_toks[i] = (int*) malloc(sizeof(int) * (segs[i].length() + 8));
      seg_len[i]  = 0;
      if (seg_toks[i])
        llm_encode(&tokenizer, segs[i].c_str(), 0, 0, seg_toks[i], &seg_len[i]);
    }
    int first = hist_n;
    total = seg_len[hist_n];
    while (first > 0 && total + seg_len[first-1] + 2 <= budget) {
      total += seg_len[first-1] + 2;
      first--;
    }
    if (total <= budget) {
      for (int i = first; i < hist_n; i++) {
        memcpy(gen.prompt_tokens + n, seg_toks[i], seg_len[i] * sizeof(int));
        n += seg_len[i];
        gen.prompt_tokens[n++] = tokenizer.eos_id;
        appendSegment("\n", budget + 8, &n);
      }
      memcpy(gen.prompt_tokens + n, seg_toks[hist_n], seg_len[hist_n] * sizeof(int));
      n += seg_len[hist_n];
    } else {
      n = (budget - 4 < seg_len[hist_n]) ? budget - 4 : seg_len[hist_n];
      memcpy(gen.prompt_tokens, seg_toks[hist_n], n * sizeof(int));
      appendSegment("\nBot:", budget + 8, &n);
    }
    for (int i = 0; i <= hist_n; i++) free(seg_toks[i]);
    gen.user_text = user_text;
  } else if (mode == M_STORY) {
    if (!appendSegment("Summary: " + user_text + "\nStory:", budget, &n)) {
      n = 0;
      appendSegment("Summary: " + user_text, budget, &n);
      if (n > budget - 4) n = budget - 4;
      appendSegment("\nStory:", budget, &n);
    }
  } else {
    if (neo) {
      appendSegment(user_text, budget, &n);
    } else {
      llm_encode(&tokenizer, user_text.c_str(), 1, 0, gen.prompt_tokens, &n);
      if (n > budget) n = budget;
    }
  }
  gen.n_prompt = n;

  if (gen.n_prompt < 1) { ui.appendBot("[empty]\n"); return; }
  gen.token       = gen.prompt_tokens[0];
  gen.pos         = 0;
  gen.next        = 0;
  gen.active      = true;
  gen.t_start_ms  = millis();
  gen.tokens_out  = 0;
  gen.bot_text    = "";
  gen.pending_nl  = false;
  gen.wrapped     = false;
  ui.beginBotReply();
}

static void finishReply() {
  gen.active = false;
  bool was_wrapped = gen.wrapped;
  if (settings.mode == M_CHAT && tokenizer.style == ARCH_GPTNEO && gen.bot_text.length())
    historyPush(gen.user_text, gen.bot_text);
  ui.endBotReply(gen.tokens_out, millis() - gen.t_start_ms);
  if (was_wrapped) {
    int total_tok = gen.tokens_out;
    historyClear();
    ui.statusf("context wrapped - %d tokens - new convo", total_tok);
  }
  if (tts_enabled && !gen.bot_text.empty()) {
    tts_speak(gen.bot_text.c_str());
  }
}

static void stepGeneration() {
  if (gen.pos >= KV_SEQ_LEN - 1) {
    if (settings.max_reply == -2) {
      gen.pos     = gen.n_prompt;
      gen.wrapped = true;
    } else {
      finishReply(); return;
    }
  }
  if (settings.max_reply >= 0 && gen.tokens_out >= settings.max_reply) {
    finishReply();
    return;
  }
  float* logits = llm_forward(&transformer, gen.token, gen.pos);

  if (gen.pos < gen.n_prompt - 1) {
    gen.next = gen.prompt_tokens[gen.pos + 1];
  } else {
    gen.next = llm_sample(&sampler, logits);
    bool is_eos = (tokenizer.style == ARCH_GPTNEO)
                      ? (gen.next == tokenizer.eos_id)
                      : (gen.next == 1 || gen.next == 2);
    if (is_eos) {
      finishReply();
      return;
    }
    char scratch[32];
    const char* piece = llm_decode(&tokenizer, gen.token, gen.next, scratch, sizeof(scratch));
    if (piece && *piece) {
      if (settings.mode == M_CHAT && tokenizer.style == ARCH_GPTNEO) {
        if (gen.pending_nl) {
          if (strncmp(piece, "User", 4) == 0) { finishReply(); return; }
          ui.appendBot("\n");
          gen.bot_text += "\n";
          gen.pending_nl = false;
        }
        if (strcmp(piece, "\n") == 0) {
          gen.pending_nl = true;
        } else {
          ui.appendBot(piece);
          gen.bot_text += piece;
        }
      } else {
        ui.appendBot(piece);
      }
    }
    gen.tokens_out++;
  }
  gen.token = gen.next;
  gen.pos++;
}

static void updateStatusBar() {
  ui.statusf("%s  T=%.1f  /new  [tab] settings",
             tts_enabled ? "TTS:ON" : "TinyChat-3M", settings.temp);
}

static void setup() {
  auto cfg = M5.config();
  M5.begin(cfg);
  Keyboard.begin();
  ui.begin();

  // GPIO0 (BOOT button) as input with pull-up.
  gpio_set_direction(GPIO_NUM_0, GPIO_MODE_INPUT);
  gpio_set_pull_mode(GPIO_NUM_0, GPIO_PULLUP_ONLY);

  ui.status("TinyStories booting...");
  initModel();

  ui.ready();
  updateStatusBar();
  state = ST_CHAT;
}

static void loop() {
  M5.update();
  Keyboard.updateKeyList();
  Keyboard.updateKeysState();

  // G0 toggle: detect falling edge (button press, active-low).
  static bool g0_prev = true;
  bool g0_now = gpio_get_level(GPIO_NUM_0);
  if (!g0_now && g0_prev && state == ST_CHAT && !gen.active) {
    tts_enabled = !tts_enabled;
    updateStatusBar();
  }
  g0_prev = g0_now;

  if (state == ST_SETTINGS) {
    if (Keyboard.isChange() && Keyboard.isPressed()) {
      auto st = Keyboard.keysState();
      if (st.tab || st.enter) { leaveSettings(); return; }
      for (char c : st.word) {
        if (c == ';') { sett_sel = (sett_sel + SETT_N - 1) % SETT_N; drawSettings(); }
        if (c == '.') { sett_sel = (sett_sel + 1) % SETT_N; drawSettings(); }
        if (c == ',') adjustSetting(-1);
        if (c == '/') adjustSetting(+1);
      }
    }
    return;
  }
  if (state != ST_CHAT) return;

  if (gen.active) {
    ui.tickGenerating(gen.tokens_out);
    if (Keyboard.isChange() && Keyboard.isPressed()) {
      auto st = Keyboard.keysState();
      for (char c : st.word) {
        if (c == '`') { finishReply(); return; }
      }
    }
    stepGeneration();
    return;
  }
  if (Keyboard.isChange() && Keyboard.isPressed()) {
    auto st = Keyboard.keysState();
    if (st.tab) {
      state = ST_SETTINGS;
      sett_sel = 0;
      drawSettings();
      return;
    }
    if (st.fn) {
      for (char c : st.word) {
        if (c == ';') ui.scrollChat(+2);
        if (c == '.') ui.scrollChat(-2);
      }
    } else {
      for (char c : st.word) ui.onChar(c);
      if (st.del)   ui.onBackspace();
      if (st.enter) {
        std::string prompt = ui.takeInput();
        if (prompt == "/new") {
          historyClear();
          updateStatusBar();
        } else if (prompt.length()) {
          ui.appendUser(prompt);
          beginGeneration(prompt);
        }
      }
    }
  }
}

extern "C" void app_main(void) {
  setup();
  for (;;) {
    loop();
    if (!gen.active) vTaskDelay(1);
  }
}
